Add MyFTSO
TowoLabs/ftso-signal-providers pull request #204
Opened 2022-09-12 08:39 UTC by virtumbe

Add MyFTSO

2022-11-02 08:31 UTC, perlindstroem requested changes
A few comments;
* The icon is not centered in the image, please fix.
* Please optimize the image with https://tinypng.com/.
* You are currently using the same address for Flare and Songbird, the best practice and recommendation is to use separate addresses, however we can accept your current setup if you want.

2022-11-02 09:11 UTC, virtumbe commented
> A few comments;
> 
> * The icon is not centered in the image, please fix.
> * Please optimize the image with https://tinypng.com/.
> * You are currently using the same address for Flare and Songbird, the best practice and recommendation is to use separate addresses, however we can accept your current setup if you want.

Did all the requested changes. Thanks in advance.

2022-11-02 12:25 UTC, perlindstroem requested changes
Great! A side-effect is that you need to have a separate copy of the image with the new address in the URI, we require one image per address.

2022-11-02 12:33 UTC, virtumbe commented
> Great! A side-effect is that you need to have a separate copy of the image with the new address in the URI, we require one image per address.

Sorry, just uploaded the requested file!

2022-11-02 12:37 UTC, perlindstroem requested changes

2022-11-02 12:37 UTC, perlindstroem commented on bifrost-wallet.providerlist.json
> +			"logoURI": "https://raw.githubusercontent.com/TowoLabs/ftso-signal-providers/master/assets/0x399a2de69e38d93bc397eb2b1f5487bd25a71c00.png"
I see that you uploaded a new image, great! However, this row also needs to mirror that update.

2022-11-04 08:36 UTC, perlindstroem approved these changes

2022-11-04 08:37 UTC, merged